:::{.callout-tip}
#### Discount Factor

The idea of using discounting in MDPs is due to @Blackwell1965.

There are two interpretations of the discount factor $γ$. The first
interpretation is an economic interpretation to determine the _present value_
of a utility that will be received in the future. For example, suppose a
decision maker is indifferent between receiving 1 dollar today or $s$ dollars
tomorrow. This means that the decision maker discounts the future at a rate
$1/s$, so $γ = 1/s$.

The second interpretation is that of an absorbing state. Suppose we
are operating a machine that generates a value of \$1 each day. However,
there is a probability $p$ that the machine will break down at the end of
the day. Thus, the expected return for today is \$1 while the expected
return for tomorrow is $(1-p)$ (which is the probability that the machine
is still working tomorrow). In this case, the discount factor is defined
as $(1-p)$. See @Shwartz2001 for a detailed discussion of this alternative.
:::
