---
title: Inventory management (revisted)
keywords:
  - inventory management
  - base-stock policy
  - reward shaping
  - structural results
  - stochastic optimization
  - infinite horizon
  - discounted cost
engine: julia
execute:
  echo: false
  cache: true
  freeze: true
---

:::{.callout-note icon=false appearance="simple"}
# <i class="bi bi-journal-text text-primary"></i> Summary
One of the potential benefits of modeling a system as infinite horizon discounted cost MDP is that it can be simpler to identify an optimal policy. We illustrate this using the inventory management example.
:::


Let's reconsider the model for [inventory management] and assume that it runs for an infinite horizon. For simplicity, we consider the case when the state and action spaces are real valued. Recall that the dynamics are given by 
$$
  S_{t+1} = S_t + A_t - W_t
$$
We take the the per-step cost to be $$c(s,a,s_{+}) = p a + γ h(s_{+}), $$ where 
$$ h(s) = \begin{cases}
  c_h s, & \text{if $s \ge 0$} \\
  -c_s s, & \text{if $s < 0$},
\end{cases}$$
where $c_h$ is the per-unit holding cost, $c_s$ is the per-unit shortage cost, and $p$ is the per-unit procurement cost. Note that we have assumed that the holding or shortage cost is discounted because this cost is incurred at the end of the time period.  

Recall that in the finite horizon setting, the optimal policy was a _base-stock_ policy characterized by thresholds $\{σ_t\}_{t \ge 1}$. In the infinite horizon discounted setting, we expect the optimal policy to be time-homogeneous, i.e., the thresholds $\{σ_t\}_{t \ge 1}$ be a constant $σ$ and not to depend on time.

```{julia}
#| output: false
# Install packages
# for pkg in ["IJulia", "Revise", "Distributions", "OffsetArrays", "DataFrames", "JSON"]
#    Pkg.add(pkg)
# end
# for url in [ "https://github.com/adityam/MDP.jl.git"]
#   Pkg.add(url=url)
# end
# # Installing Jupyter Cache
# Pkg.add("Conda")
# using Conda
# Conda.add("jupyter-cache")

using Revise

using Distributions: Exponential, Binomial, pdf, cdf
using OffsetArrays
using MDP
using DataFrames, JSON3
```

As an illustration, let's reconsider the example used for the [finite horizon
setting][finite] (where $c_h = 2$, $c_s = 5$, $p=1$, and the demand is
Binomial(50,0.4)). We consider the discount factor $γ = 0.9$. The value
function and optimal policy is this case are shown below.

[finite]: inventory-management.html#fig1

```{julia}
#| output: false

function generate_binomial_demand(n,q,ch,cs,p,γ)
  Pw = Binomial(n,q)
  h(s) = (s >= 0) ? ch*s : -cs*s

  L = 2n
  S = -L:L
  A = 0:2L+1
  W = 0:n

  function bellmanUpdate!(v_next, π_next, v; discount=1.0)
      # Assume that v is of size 2L + 1
      # Construct a post-decision state value function
      H = OffsetArray(zeros(3L+1),-L:2L)
      # h(z) = E[ h(z-W) + γ V(z-W) ]
      for z ∈ -L:2L, w ∈ W
          next_s = clamp(z-w, -L, L)
          H[z] += ( h(z-w) + discount * v[next_s] )* pdf(Pw,w)
      end

      # V(s) = min_{a } { p*a + H(s+a) }
      for s ∈ S
          opt = 0
          val = H[s]

          for a ∈ A
              next_z = clamp(s+a, -L, 2L)
              newVal = p*a + H[next_z]
              if newVal <= val
                  opt = a
                  val = newVal
              end
          end
          v_next[s] = val
          π_next[s] = opt
      end
  end

  model = DynamicModel(bellmanUpdate!; objective=:Min)
  v_initial = OffsetArray(zeros(size(S)), S)
  (V, π) = valueIteration(model, v_initial, discount=γ)

  return (S,V,π)
end
```

```{julia}
#| output: false
df_bin = DataFrame(state=Float64[], value=Float64[], policy=Float64[], holding=Float64[], shortage=Float64[])

Ch_bin = range(start=0.5, step=0.5, stop=5.0)
Cs_bin = range(start=0.5, step=0.5, stop=5.0)
for ch in Ch_bin, cs in Cs_bin
 (S,V,π) = generate_binomial_demand(50, 0.4, ch, cs, 1., 0.9)
 for s in S
    push!(df_bin, (s, V[s], π[s], ch, cs))
 end
end
```

```{julia}
ojs_define(binomial = df_bin)
```

```{ojs}
//| layout-ncol: 2
viewof ch_bin = Object.assign(Inputs.range([0.5, 5], {label: "ch", step: 0.5, value: 2.0 }), {style: '--label-width:20px'})
viewof cs_bin = Object.assign(Inputs.range([0.5, 5], {label: "cs", step: 0.5, value: 5.0 }), {style: '--label-width:20px'})
```

```{ojs}
//| layout-ncol: 2
//| fig-cap: Optimal policy for the model with binomial demand. 
//| fig-subcap:
//|     - Value function
//|     - Optimal policy

ValuePlotBin = Plot.plot({
  grid: true,
  x: { domain: [-30, 70] },
  y: { domain: [200, 400] },
  marks: [
    // Axes
    Plot.ruleX([0]),
    // Plot.ruleY([0]),
    // Data
    Plot.line(binomial.filter(d => d.shortage == cs_bin && d.holding == ch_bin),
              {x: "state", y: "value", stroke: "black"}),
  ]}
)

PolicyPlotBin = Plot.plot({
  grid: true,
  x: { domain: [0, 30] },
  y: { domain: [0, 30] },
  marks: [
    // Axes
    Plot.ruleX([0]),
    // Plot.ruleY([0]),
    // Data
    Plot.line(binomial.filter(d => d.shortage == cs_bin && d.holding == ch_bin),
              {x: "state", y: "policy", stroke: "black"}),
  ]}
)
```

---

We are interested in the following question: _Is it possible to identify the optimal threshold of the base-stock policy without explicitly solving the dynamic program?_ In this section, we show that the answer is affirmative.

As was the case for the finite horizon, we use a post-decision state formulation where we take $Z_t = S_t + A_t$ as the post-decision state. The corresponding dynamic program is given by the following coupled fixed point equations:
\begin{align*}
  H(z) &= \EXP[ h(z - W) + V^*(z - W) ] \\
  V^*(s) &= \min_{a \in \reals_{\ge 0}} \bigl\{ pa + γ H(s+a) \}
\end{align*}
with the optimal time-homogeneous policy given by 
$$
  π^*(s) = \arg \min_{a \in \reals_{\ge 0}} \bigl\{ pa + γ H(s+a) \}
$$

Suppose we find the fixed point by starting from an initial guess $V_0(s) = 0$ and iteratively computing $\{ V_t \}_{t \ge 0}$ and $\{H_t \}_{t \ge 0}$. Then from the result of @thm-inventory-structure, we know that $V_t$ and $H_t$ are convex and have the structure given in @thm-inventory-structure. Therefore, the limit will also have these properties. 

In particular, define
$$
  f(z) = pz + γ H(z)
$$
Then, 
$$
 V^*(s) = \min_{a \in \reals_{\ge 0}} f(s+a) - p s
 = f(\max\{s, σ\}) - ps
 $$ 
 where
$$
  σ = \arg \min_{z \in \reals} f(z)
$$

Therefore, we have

\begin{align*}
  f(z) &= pz + γH(z) \\
  &= pz + γ \EXP[h(z - W)] + γ \EXP[ V^*(z - W)] \\
  &= (1 - γ) p z + γ p μ + γ \EXP[ h(z - W) ] + γ \EXP[ f(\max\{z - W, σ\}) ]
\end{align*}
where $μ = \EXP[W]$. For the ease of notation, define
$$
  c^*(z) = (1 - γ) p z + γ \EXP[h(z - W)] + γ p μ
$$
Then, we have
\begin{equation}\label{eq:F}
  f(z) = \EXP[c^*(z - W)] + γ \EXP[ f(\max\{s - W, σ\})]
\end{equation}

The main result is the following.

::: {#lem-inventory-threshold}
$f(z)$ and $\EXP[c^*(z-W)]$ have the same minimizer, i.e.,
$$
  \arg\min_{z \in \reals}f(z) 
  = \arg\min_{z \in \reals}\EXP[c^*(z-W)]
$$
Therefore,
$$
  σ = \arg\min_{z \in \reals}\EXP[c^*(z-W)]
$$
:::

:::{.callout-note collapse="true"}
### Solution

For the ease of notation, we define $g(z) = \EXP[c^*(z - W)]$ and $\bar f(z) = \EXP[f(\max\{z - W, σ\})$. Then, \eqref{eq:F} can be written as
$$
  f(z) = g(z) + γ \bar f(z)
$$
We know that all three functions are convex. Moreover, $σ$ is a minimizer of $f$. Thus, 
$$
  0 \in ∂ f(σ)
  \iff
  f'_{-}(σ) \le 0 \le f'_{+}(σ).
$$
We will show that
$$
  0 \in ∂ g(σ)
  \iff
  g'_{-}(σ) \le 0 \le g'_{+}(σ).
$$

**Left derivative:** Since the demand $W \ge 0$, we have $\bar f(z) = f(σ)$ for $z \le σ$. Thus, 
$$
  f(z) = g(z) + γ f(σ), \quad z \le σ
$$
which implies that
$$
  g'_{-}(z) = f'_{-}(z) = 0.
$$

**Right derivative:** By dominated convegence theorem, we can interchange derivatives and expectation. Therefore, 
$$
  \bar f'_{+}(z) = \EXP[ f'_{+}(z - W) \IND\{ z - W \ge σ \} ], \quad z \ge σ.
$$
Thus,
$$
  \bar f'_{+}(σ) = f'_{+}(σ) \PR(W = 0).
$$

Taking the right derivative of $f(z) = g(z) + γ \bar f(z)$, we get
$$
f'_{+}(σ) = g'_{+}(σ) + γ f'_{+}(σ) \PR(W = 0)
\implies
g'_{+}(σ) = f'_{+}(σ)(1 - γ \PR(W = 0)) 
$$
We know that $f'_{+}(σ) \ge 0$ and $(1 - γ\PR(W = 0)) \ge 0$. Thus, 
$$
  g'_{+}(σ) \ge 0.
$$

Hence, $σ$ is a minimizer of $g$. 
:::

::: {#thm-inventory-inf}
The optimal threshold $σ$ is given by the value of $σ$ which minimizes $\EXP[ c^*(σ-W) ]$. In particular, if $F$ denotes the CDF of the demand, then
$$\begin{equation}
 σ = F^{-1}\left( \frac{c_s - p(1-γ)/γ}{c_h + c_s} \right).
 \label{eq:opt-threshold}
\end{equation}$$
::: 

::: {.callout-note collapse="false"}
#### Proof {-}
The proof idea is the same approach as that used for the [newsvendor
problem][newsvendor]. In particular, let $f_W$ denote the
distribution of $W$, $F$ denote the CDF, and $μ = \EXP[W]$. Then,
\begin{align*}
\EXP[c^*(σ-W)] &= γ\EXP[h(σ-W)] + (1-γ) \EXP[p(σ - W)] + γ p μ \\
&= γ \EXP[h(σ - W)] + (1-γ)p σ + p μ
\\
&= γ \int_{0}^{σ} c_h(σ-w)f_W(w)dw + 
   γ \int_{σ}^{∞} c_s(w-σ)f_W(w)dw \\
&\quad + (1-γ)p σ + p μ
\end{align*}
Thereore, 
\begin{align*}
\frac{∂ \EXP[c^*(σ-W)]}{∂σ} &=
  γ \int_{0}^{σ} c_h f_W(w)dw
+ γ\int_{σ}^{\infty}[-c_s] f_W(w)dw 
+ (1-γ)p \\
&= γ c_h F(σ) - γ c_s(1 - F(σ)) + (1-γ) p 
\end{align*}
To find the optimal threshold, we set the derivative to $0$ and simplify to
obtain \\eqref{eq:opt-threshold}.
:::

We can use \\eqref{eq:opt-threshold} to find the optimal threshold for the example used above. In particular, we need to find the value of $σ$ at which the CDF of the demand equals the value $(c_s - p(1-γ)/γ)/(c_h + c_s)$, as shown in @fig-threshold below.

```{julia}
#| output: false
function generate_demand()
  n, q = 50, 0.4
  ch, cs, p = 2, 5, 1

  Pw = Binomial(n,q)

  demand_df = DataFrame(demand=Float64[], probability=Float64[], cumulative=Float64[])
  for k in 0:n
    push!(demand_df, (k, pdf(Pw,k), cdf(Pw,k)) )
  end
  return demand_df
end
demand_df = generate_demand()
```

```{julia}
ojs_define(W = demand_df)
```

```{ojs}
//| layout-ncol: 2
viewof ch_val = Object.assign(Inputs.range([0.5, 5], {label: "ch", step: 0.5, value: 2.0 }), {style: '--label-width:20px'})
viewof cs_val = Object.assign(Inputs.range([0.5, 5], {label: "cs", step: 0.5, value: 5.0 }), {style: '--label-width:20px'})
```


```{ojs}
p  = 1
discount = 0.9
F_opt = (cs_val - p*(1-discount)/discount)/(ch_val + cs_val)
```

```{ojs}
//| fig-cap: The optimal threshold for the example shown above.
//| label: fig-threshold
demand_CDF_plot = Plot.plot({
  grid: true,
  marks: [
    // Axes
    Plot.ruleX([0]),
    Plot.ruleY([0]),
    // Data
    Plot.line(W, {x:"demand", y:"cumulative",curve:"step-after"}),
    Plot.line([ [0,F_opt], [W[W.length-1].demand, F_opt] ], {stroke: "red"})
  ]
})
```

---

## Exercises {-}

```{julia}
#| output: false

function generate_exponential_demand(μ, ch, cs, p, γ)
  discount = γ 

  δ = 0.1
  L = 100

  S = -L:L
  A = 0:2L+1
  W = 0:min(L,300)

  point(ℓ) = ℓ * δ

  Pw_true = Exponential(μ)
  Pw = OffsetArray(zeros(size(W)), W)
  for w ∈ W
      if w != W[end]
          Pw[w] = cdf(Pw_true, point(w+1)) - cdf(Pw_true, point(w))
      else
          Pw[w] = 1 - cdf(Pw_true, point(w))
      end
  end

  h(s) = (s >= 0) ? ch*s : -cs*s

  function bellmanUpdate!(v_next, π_next, v; discount=1.0)
      # Assume that v is of size 2L + 1
      # Construct a post-decision state value function
      H = OffsetArray(zeros(3L+1),-L:2L)
      # h(z) = E[ h(z-W) + γ V(z-W) ]
      for z ∈ -L:2L, w ∈ W
          next_s = clamp(z-w, -L, L)
          H[z] += ( h(z-w) + discount * v[next_s] )*Pw[w]
      end
  
      # V(s) = min_{a } { p*a + H(s+a) }
      for s ∈ S
          opt = 0
          val = H[s]
  
          for a ∈ A
              next_z = clamp(s+a, -L, 2L)
              newVal = p*a + H[next_z]
              if newVal <= val
                  opt = a
                  val = newVal
              end
          end
          v_next[s] = val
          π_next[s] = opt
      end
  end
  model = DynamicModel(bellmanUpdate!; objective=:Min)
  v_initial = OffsetArray(zeros(size(S)), S)

  (V,π) = valueIteration(model, v_initial; discount=discount)

  threshold = μ * log( (ch + cs) / (ch + p*(1-discount)/discount) )
  return (δ,S,V,π,threshold)
end

df_exp = DataFrame(state=Float64[], value=Float64[], policy=Float64[], holding=Float64[], shortage=Float64[])

df_threshold = DataFrame(threshold=Float64[], holding=Float64[], shortage=Float64[])

Ch_exp = range(start=0.5, step=0.5, stop=5.0)
Cs_exp = range(start=0.5, step=0.5, stop=5.0)
for ch in Ch_exp, cs in Cs_exp
 (δ,S,V,π,threshold) = generate_exponential_demand(5, ch, cs, 1., 0.9)
 for s in S
    push!(df_exp, (s*δ, V[s], π[s], ch, cs))
 end
 push!(df_threshold, (threshold, ch, cs))
end
```

```{julia}
ojs_define(exponential = df_exp, threshold_exp = df_threshold)
```


:::{#exr-inventory-exponential}
Suppose that the arrival process is exponential with rate $1/\mu$, i.e.,
the density of $W$ is given by $e^{-s/\mu}/\mu$. Show that the optimal
threshold is given by
$$ σ = \mu \log \left[ \frac{ c_h + c_s} { c_h + p (1-γ)/γ} \right]. $$

 _Hint_: Recall that the CDF the exponential distribution is
 $F(s) = 1 - e^{-s/μ}$.
:::

The plots below verify this result numerically. We simulate the system with parameters $μ = 5$, $p = 1$, $γ = 0.9$. 

```{ojs}
//| layout-ncol: 2
viewof ch_exp = Object.assign(Inputs.range([0.5, 5], {label: "ch", step: 0.5, value: 2.0 }), {style: '--label-width:20px'})
viewof cs_exp = Object.assign(Inputs.range([0.5, 5], {label: "cs", step: 0.5, value: 5.0 }), {style: '--label-width:20px'})
```

```{ojs}
//| fig-cap: Optimal policy for model with exponential demand. The black curve shows the optimal policy computed via value iteration and the red line shows the threshold computed via the formula of @exr-inventory-exponential.

ValuePlotExp = Plot.plot({
  grid: true,
  x: { domain: [-11, 11] },
  y: { domain: [0, 200] },
  marks: [
    // Axes
    Plot.ruleX([0]),
    Plot.ruleY([0]),
    Plot.ruleX(threshold_exp.filter(d => d.shortage == cs_exp && d.holding == ch_exp), 
               {x: "threshold", stroke: "red"} ),
    // Data
    Plot.line(exponential.filter(d => d.shortage == cs_exp && d.holding == ch_exp),
              {x: "state", y: "policy", stroke: "black"}),
  ]}
)
```

## Notes {-}

As far as I know, the explicit formula of the threshold presented in @thm-inventory-inf has not appeared in the literature before. A partial version of this result is presented in @Whittle1982, using essentially the idea of [reward shaping]. It is interesting to note that @Whittle1982 uses the idea of reward shaping more than 17 years before the paper by @Ng1999 on reward shaping. It is possible that Whittle was using the results of @Porteus1975. 

As established in the notes on [Lipschitz MDPs], it can be shown that the optimal value function for the inventory management model above is Lipschitz continuous.

In the analysis above, we did not formally verify that all the functions exist and infinimizations were well defined. For a detailed discussion of such technical details, see @Feinberg2016.

For the models with [positive ordering cost](inventory-management.qmd#positive-ordering-cost) an efficient algorithm for computing the optimal $(s,S)$ policy is presented in @Zheng1991.

[inventory management]: inventory-management.qmd
[reward shaping]: reward-shaping.qmd
[Lipschitz MDPs]: lipschitz-mdps.qmd#inventory-example
[newsvendor]: ../stochastic-optimization/intro.qmd#newsvendor

