---
title: Examples of monotonicity
---

:::{.callout-note icon=false appearance="simple"}
# <i class="bi bi-journal-text text-primary"></i> Summary
In this section, we present several examples to illustrate that the dynamic programming formulation can be used to identify qualitative properties of the value function and optimal policies.
:::


{{< include monotone-examples/power-delay-tradeoff.qmd >}}

## Exercises {-}

::: {#exr-power-delay-monotone}

Suppose that the channel state $\{S_t\}_{t \ge 1}$ is an i.i.d. process. Then prove that for all time $t$ and queue state $x$, there is an optimal strategy $π^*_t(x,s)$ which is decreasing in channel state $s$.

:::

## Notes {-}

The mathematical model of power-delay trade-off is taken from @Berry2000,
where the monotonicty results were proved using first principles.
More detailed characterization of the optimal transmission strategy when the
average power or the average delay goes to zero are provided in @Berry2002 and
@Berry2013. A related model is presented in @Ding2016.

For a broader overview of power-delay trade offs in wireless communication,
see @Berry2012 and @Yeh2012.

The remark after @lem-power-delay-submodular shows the difficulty in establishing monotonicity of optimal policies for a multi-dimensional state space. In fact, sometimes even when monotonicity appears to be intuitively obvious, it may not hold. See @Sayedana2020a for an example. For general discussions on monotonicity for multi-dimensional state spaces, see @Topkis1998 and @Koole2006. As an example of using such general conditions to establish monotonicity, see @Sayedana2020. 





