project:
  type: website
  render:
    - solutions.qmd
    - solutions/01.qmd
    - solutions/02.qmd
    - solutions/03.qmd
    - solutions/04.qmd
    - solutions/05.qmd
    - solutions/06.qmd
    - solutions/07.qmd

format:
  html:
    author:
      - name: Aditya Mahajan
        url: https://adityam.github.io
        affiliation: McGill University
        affiliation-url: http://www.mcgill.ca/ece
    theme: 
      light: 
        - lumen
        - static/css/style.scss
      dark: 
        - darkly
        - static/css/style.scss
    include-in-header: 
      - static/html/mathjax.html
      - static/html/clicky.html

    published-title: Updated
    date: last-modified
    notebook-links: inline

    embed-resources: true
