---
listing:
  id: summary
  template: ejs/links.ejs
  contents: summary.yml

aliases:
  - notes/index.html

course:
  term: "Winter 2026"
  office-hours: "TBD"
  mid-term: "13 March"
  lectures:
    - "4:05pm–5:35pm Wednesday, Friday (Wong 1030)"

format: 
  html: 
    number-sections: false
---

# Course Outline {.unnumbered}

## General Information ({{< meta course.term >}})

Instructor
: -  Aditya Mahajan 
- *Office Hours*: {{< meta course.office-hours >}}

Lectures
: - {{< meta course.lectures >}} 

Prerequisites
: - ECSE 509 (Graduate Probability)

Communication
: [Use the discussion board on myCourses]{.text-info} for all questions related to the course. Only personal emails related to medical exceptions for missing a deliverable will be answered.

## Course Content

The objective of the course is to provide the background necessary to read and understand research papers in stochastic control and reinforcement learning. Therefore, the emphasis is on understanding the intuition and the details of the proof. We will go through all the proofs in class. 

We will also study examples from different application domains: communications, operations research, control systems, and power systems, with an emphasis on modeling and establishing qualitative properties of the optimal solution.


| Week | Material Covered | 
|------|:-----------------|
| 1    | [Stochastic optimization](stochastic-optimization/intro.qmd) and [dealing with observations](stochastic-optimization/observations.qmd) |
| 2    | [Finite horizon MDPs](mdps/intro.qmd), [optimal gambling](mdps/gambling.qmd)  | 
| 3    | [Proof of optimality of DP decomposition](mdps/intro.qmd), [post decision state and inventory management](mdps/inventory-management.qmd)  |
| 4    | [Monotonicity of value function and policy](mdps/monotone-mdps.qmd) and [examples of monotonicity](mdps/power-delay-tradeoff.qmd) |
| 5    | [Infinite horizon MDPs and Bellman operators](mdps/inf-horizon.qmd) |
| 6    | [MDP algorithms](mdps/mdp-algorithms.qmd) and [approximate dynamic programming](approx-mdps/approx-mdps.qmd)|
| 7    | Review and Mid-Term | 
| 8    | [Lipschitz MDPs](mdps/lipschitz-mdps.qmd) and [model approximation](approx-mdps/model-approximation.qmd) | 
| 9    | [Linear function approximation](approx-mdps/linear-function.qmd)
| 10    | [POMDPs and information state](pomdps/intro.qmd) | 
| 11   | [Belief state MDP](pomdps/intro.qmd) and [sequential hypothesis testing](pomdps/sequential-hypothesis.qmd) | 
| 12   | [Agent state based policies](pomdps/agent-state.qmd) and [conservative policy iteration](pomdps/pocpi.qmd) |
| 13   | [Dec-POMDPs](dec-pomdps/designers-approach.qmd) | 

: {tbl-colwidths="[10,90]" .striped}



<!--
::: {#summary .column-screen-inset-right style="max-width: 850px;"}
:::
-->

## Course Material

The material for the lecture notes is taken from various sources, including the reference books listed below. If you find any typos/mistakes in the notes, please let me know. [Pull requests are welcome](https://github.com/adityam/stochastic-control/tree/quarto).

### Reference books

-   Kumar and Varaiya, [*Stochastic Systems: Estimation,
    Identification, and Adaptive
    Control,*](http://bookstore.siam.org/cl75/) Prentice Hall, 1986.
    Reprinted by SIAM 2015
    <br />
    A gentle introduction which emphaisizes the key conceptual ideas.

-   Bertsekas, [*Dynamic programming and optimal
    control*,](http://www.athenasc.com/dpbook.html) vol 1 and
    2, Athena Publications, 2005.
    <br />
    Perhaps the most comprehensive book of different topics in
    dynamic programming.

-   Puterman, [*Markov decision processes: discrete time dynamic
    programming*](http://onlinelibrary.wiley.com/book/10.1002/9780470316887), Wiley 1994.
    <br />
    Excellent source algorithms for perfectly observed systems, in
    particular, infinite horizon dynamic programs.

-   Ross, [*Introduction to Stochastic Dynamic
Programming,*](https://www.elsevier.com/books/introduction-to-stochastic-dynamic-programming/ross/978-0-12-598420-1) Academic
    Press, 1983.
    <br />
    Excellent introduction to dynamic programming, from the
    point-of-view of applied mathematics.

-   Dernardo, *Dynamic Programming: Models and Applications,*
    Prentice Hall, 1982.
    <br />
    Excellent introduction to dynamic programming, from the
    point-of-view of operations research.

-   Powell, [*Approximate Dynamic Programming*](http://adp.princeton.edu),
    John Wiley and Sons, 2011.
    <br />
    Comprehensive overview of approximate dynamic programming

-   Krishnamurty, [*Partially Observable Markov Decision
    Processes*](https://www.cambridge.org/core/books/partially-observed-markov-decision-processes),
    Cambridge University Press, 2016.
    <br />
    Comprehensive overview of POMDPs

-   Sargent and Stachurski, [*Dynamic Programming*](https://dp.quantecon.org/), 2023.
    <br />
    Nice summary of DP ideas applied to economic models. Good mix of theory and numerical examples. 

-   Kochenderfer, Wheeler, and Wray, [*Algorithms for decision making*](https://algorithmsbook.com/),
    MIT Press, 2022. 
    <br />
    Broad introduction to decision making under uncertainty. Lots of nice examples.

## Evaluation

- **Assignments (30%)** Weekly homework assignments. Typically, each assignment will consist of four or five questions, out of which [one or two randomly selected questions will be graded]{.text-danger}. 

- **Mid Term (25%)** Closed book in-class exam.
  [**{{< meta course.mid-term >}}**]{.text-danger} (during class time)

- **Term Project (20%)** A month long term project to be done in groups of two. Present one paper or book chapter on any topic of your interest related to the material covered in class. 

- **Final Exam (25%)** Closed book, in-person exam. Will be scheduled by the exam office and the dates will be announced later.

    The final exam will cover **all** the material seen in the class during the term.

## Marking policy

- Assignments must be submitted electronically on myCourses as a PDF. You may write the assignments on paper and then scan them as a PDF (there are several such apps available for all phone platforms), or write on a tablet and convert to PDF, or type using a word processor.

- **There will no make-up examination** for students who miss a mid-term.

  - Student who miss the exam due to a valid reason (see [Faculty of Engineering policy][policy]) should **notify the instructor within a week** of the exam and provide **necessary documentation**.

  - If, and only if, proper documentation for a missed exam is presented, the marks for the missed exam will be shifted to the final exam.

  - Students who miss the mid-term exam for any other reason (e.g., no medical note, going to the exam at the wrong time, or on the wrong day, etc.) will get zero marks on the exam.

- Any request for reevaluation of a mid-term or an assignment must be made **in writing within a week of its return**. Note that requesting a re-grade will mean that you **WHOLE** assignment or exam will be re-graded.


Right to submit in English or French written work that is to be graded.
: In accord with McGill University’s [Charter of Students’ Rights][charter], students in this course have the right to submit in English or in French any written work that is to be graded.

Academic Integrity
: McGill University values academic integrity. Therefore all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the [Code of Student Conduct and Disciplinary Procedures][code] (see McGill’s [guide to academic honesty][guide] for more information).

    L’université McGill attache une haute importance à l’honnêteté académique. Il incombe par conséquent à tous les étudiants de comprendre ce que l’on entend par tricherie, plagiat et autres infractions académiques, ainsi que les conséquences que peuvent avoir de telles actions, selon le [Code de conduite de l’étudiant et des procédures disciplinaires][code] (pour de plus amples renseignements, veuillez consulter le [guide pour l’honnêteté académique][guide] de McGill.)

## Course delivery

The course is taught in a “chalk and board” style; there will be no power point presentations. All students are expected to attend lectures and take notes. Partial notes on some of the material will be provided, but are not a substitute for the material covered in class.

© Instructor-generated course materials (e.g., handouts, notes, summaries, exam questions) are protected by law and may not be copied or distributed in any form or in any medium without explicit permission of the instructor. Note that infringements of copyright can be subject to follow up by the University under the Code of Student Conduct and Disciplinary Procedures.

## Additional Notes

- As the instructor of this course I endeavor to provide an inclusive learning environment. However, if you experience barriers to learning in this course, do not hesitate to discuss them with me or contact the office of [Student Accessibility and Achievement][OSD].

- [End-of-course evaluations][evaluations] are one of the ways that McGill works towards maintaining and improving the quality of courses and the student’s learning experience. You will be notified by e-mail when the evaluations are available. Please note that a minimum number of responses must be received for results to be available to students.


[policy]: https://www.mcgill.ca/engineering/students/undergraduate/courses-registration/exams-assessment/midterms-and-class-tests/adjustments-missed-midterms-and-class-tests

[charter]: https://www.mcgill.ca/secretariat/files/secretariat/charter_of_student_rights_last_approved_october_262017.pdf

[code]: https://www.mcgill.ca/secretariat/files/secretariat/code_of_student_conduct_and_disciplinary_procedures.pdf

[guide]: http://www.mcgill.ca/students/srr/honest/

[evaluations]: http://www.mcgill.ca/mercury/

[OSD]: https://www.mcgill.ca/access-achieve/



## How to cite these notes

To cite these lecture notes, please use:

```
@misc{506notes,
  author        = {Aditya Mahajan},
  title         = {Lecture notes on Stochastic Control and Decision Theory},
  year          = {2026},
  howpublished  = "\url{https://adityam.github.io/stochastic-control/}",
}
```
