---
csl: _extensions/csl/acm-siggraph-in-text-full.csl
link-citations: false

course:
  presentation:
    date: "20 April, 2026 from 2pm to 5pm @ ARTS W20"
    weight: "5%"
  report:
    date: "26 April 2026"
    weight: "15%"

---

The term project consists of two components: project presentation (scheduled {{< meta course.presentation.date >}}) worth {{< meta course.presentation.weight >}} and a report (due {{< meta course.report.date >}} worth {{< meta course. report.weight >}}

# Grading rubric for the report

The report must be typeset in single-column format with 1 inch margin. Use 11pt font with single spacing. The expected length of the report is 12-15 pages, but you may submit a slightly shorter or slight longer report. However, excessively long reports will be penalized. The objective of the report is not to reproduce all the results in the paper, but to summarize and highlight the key results.

The report should use the following outline:



1. **Introduction (5 marks)**

    - Explain the problem addressed in the chosen literature and why it is significant.
    - Present a short summary of the solution approach and the primary results. 

2. **System Model (15 marks)**
  
    - Provide a precise description of the model or framework presented in the paper. 
    - Discuss how this model relates to the concepts and methods covered in this course.
    - Explain the key conceptual or technical difficulty the authors aimed to resolve in analyzing this model.

3. **Main results (30 marks)**

    - Clearly state the main result(s).
    - Provide a complete proof or a sufficiently detailed outline. The explanation should be clear enough for a classmate to understand the mathematical or logical progression without needing the original paper.
    - Identify the specific steps in the analysis that address the technical challenges highlighted in Section 2.

4. **Illustrative examples (20 marks)**

    - Provide two or more examples that clearly illustrate the results. 
    - Provide the code used to generate these examples, accompanied by a README file explaining how to run it. Follow standard practices for specifying dependencies (e.g., a requirements file).
    - Connect these examples back to the challenges identified in Section 2. Do the results effectively address those difficulties?

5. **Conclusion (10 marks)**

    - Summarize the key results and their implications.
    - Place the work in the context of the wider literature. Has this led to follow-up research or changed how these problems are approached?

In addition to these section, the following additional grades will be allocated:

- **Clarity of presentation (5 marks)**

   Use clear, concise language free of grammatical and typographical errors. All equations and figures must be properly formatted.

- **Critical analysis of the results (15 marks)**

   This grade evaluates the depth of the discussion across Sections 2, 3, and 4. It focuses on:

   - An evaluation of the assumptions made in the paper. Are they restrictive? Are they realistic for the problem described?
   - A discussion on the boundaries of the findings. Where does the theory break down, or what cases does the paper fail to cover?
   - Does the chosen approach offer the most efficient solution, or are there obvious trade-offs in complexity or performance?

# Potential Project Topics {.unnumbered}

The project must be done in groups of two. The idea is to review a paper or book chapter corresponding to the material covered in class and give a 15 minute presentation and a 10-15 page report on the topic.

Below is a (non-exhaustive) list of potential project topics.

### Variations of MDP models

- **Average cost MDPs**

    We restricted attention to discounted cost setting in class. Another infinite horizon objective is the average cost setting. A potential term project on this topic would be to cover the derivation of the average cost dynamic program under weak accessibility conditions and discuss the variations of value iteration, policy iteration, and linear programming and a discussion of the vanishing discount approach. This is covered in all standard books: 
    
    > @KumarVaraiya1986

    > @Puterman2014

    > @Bertsekas:book. 

    > @Sennott:book

- **Regularization in MDPs**

    Regularization is commonly used in many reinforcement learning algorithms. A potential term project on this paper will be to discuss the overview presented in 

    > @Geist2019

- **Event driven optimization**

    In the models discussed in class, decisions need to be made at every time. One way to reduce the computational complexity is to consider the setting where decisions are made only when certain events occur. An overview of this approach is presented in 

    > @Cao2005 
    
    For a full treatment see

    > @Cao2007

- **Constrained MDPs**

    In class, we briefly discussed constrained MDPs. A term project on this topic would be to provide complete details for the discounted case, using for example, Altman's book:

    > @Altman1999 

    A variation will be to provide an overview of what is called the convex analytic approach introduced in 

    > @Borkar1988 

    An accessible introduction is presented in 

    > @Borkar2002

- **Periodic MDPs**

    In class, we restricted attention to time-homogeneous models. In practice, especially in applications like power systems, the dynamics are often periodic. A potential term project on this topic will include an overview of the main ideas of periodic MDPs introduced in

    > @Riis1965

    An accessible overview is provided in

    > @Scherrer2016

- **Risk-sensitive MDPs**

    In the course, we primarily restricted to risk neutral setup. In many settings, we are interested in [risk sensitive utility](risk-sensitive/risk-sensitive-utility.qmd) function. A potential term project could be to review the formulation of risk sensitive MDPs (links to be added).

- **Distribution of returns**

    In the course, we focused on the expected returns. In some settings, one is interested in the distribution of returns. Surprisingly, it is possible to write a dynamic programming for the distribution of returns. A potential term project on this topic could be to review Chapters 2 and 5 of the following book:

    > @Bellemare2023

### Structural properties of MDPs

- **Establishing properties beyond monotonicity**

    In the class, we studied sufficient conditions for value function and policy to be monotone. But what about other properties such as convexity? 

    A general theory for when such structural properties can be established is presented in 

    > @Smith2002

    A related result is the theory of comparative statistics, which establishes monotonicity in any model parameter (including discount factors)

    > @Light2021

    A specific example of these types of result are sufficient conditions under which optimal stopping problems have a "control band" type structure: continue as long as the state is within an interval, otherwise stop.
 
    > @Oh2016 

- **Monotonicity for multi-dimensional MDPs**

    In class, when discussing monotonicity results, we assumed that the state is one-dimensional. The general theory for multi-dimensional setting is presented in the following
  
    > @Topkis1998

    These can be difficult to use. Easier to verify conditions (for a specific class of models) are presented in 
    
    > @Papadaki2007

    A systematic treatment for queueing models is presented in 
    
    > @Koole2006

- **Structural results for POMDPs**

    In class, we only discussed structural results for MDPs. A general theory of POMDPs is preseted in part III of the following book:

    > @Krishnamurthy2025

- **Multi-armed bandits**

    Multi-armed bandits[^MAB] are a special class of resource allocation problems which have a low complexity solution. In general, scheduling problems can be modeled as MDPs, but the state space of such problems in exponential in the number of alternatives. This is sometimes referred to as the _curse of dimensionality_. A conceptual breakthrough in such problems was achieved when Gittins showed that 
    a low complexity solution exists. 

    > @Gittins1974

    > @Gittins1979 

    [^MAB]: There are two classes of models that go under the heading of multi-armed bandits. One is the class of models that I have described here. The second are a different class of models which build on the work of Lai and Robbins

      > @LaiRobbins1985

      which derived regret bounds for such models. These days the latter class of models are more popular, primarily because they have been used extensively in algorithms which display online advertisements. 

    A potential term project on this topic is to review the basic result of @Gittins1979. The proof in @Gittins1979 uses [interchange argument](stochastic-optimization/interchange.qmd), which we did not cover in the course. So the term project could cover the method of interchange arguments, and then explain Gittins result using that. 

    Another alternative is to present the dynamic programming proof of Gittins result, which was presented in

    > @Whittle1980

    Since then multiple proofs of Gittins result have been presented in the literature. A survey of the four most popular results is presented in 

    > @Frostig2016

    Another potential term project is to present the restart-in-state formulation of the multi-armed problem presented in 

    > @Katehakis1987

    An interesting generalization of this idea for multi-armed bandits with commitments is presented in 

    > @Cowan2015

- **Structure-aware reinforcement learning**

   There are many papers which leverage the structural properties of MDPs to develop "structure-aware" RL algorithms, which in general converge much faster than general RL algorithm. A non-exhaustive list is given below:

   > @Subramanian2020

   Provides an RL algorithm for MDPs where the Markov chain under the optimal policy has a renewal structure. A term project on this topic could include an overview of renewal theory for stochastic processes and tie that to the results presented in the above paper.

   > @Roy2022

   Provides variation of actor-critic algorithms for MDPs with a threshold structure. 

   > @Jitani2022

   An application of the results of @Roy2022 for node overload protection in mobile edge computing.

   > @Fu2012

   Provides a variation of Q-learning for a slight variation of the model presented in [power-delay tradeoff](mdps/power-delay-tradeoff.qmd)

   > @Kunnumkal2008

   Proposes a variation of Q-learning algorithm for monotone MDPs.



### MDP Algorithms

- **Stochastic dual dynamic programming (SDDP)**

    SDDP is an efficient way to solve MDPs in continuous spaces using ideas from mathematical programming. An accessible overview is presented in

    > @Shapiro2011 

- **Information relaxation**

    The idea behind information relaxation is to assume that we can relax the non-anticipativity constraints (so, we assume that we can observe the future random variables at a cost). Such a relaxation provides a lower bound on optimal performance. By appropriately tuning the cost of observation, one can obtain tighter bounds. An overview of the main theory is presented in this monograph:

    > @Brown2022

- **Improved MDP algorithms**

    It is possible to improve value iteration based on bounds on the optimal value function. An instance of this idea is presented in:

    > @Porteus1975

    Another instance is the reward balancing procedure presented in:
    
    > @Mustafin2025

    Another idea is to use operator splitting from linear algebra to modify value and policy iteration.

    > @Rakhsha2022

- **Policy gradient algorithms**

    A variation of policy iteration is using gradient descent on the policy parameters. The performance is usually not convex in the policy parameters, which makes it difficult to establish convergence of such algorithms. A comprehensive overview is provided in

    > @Agarwal2020

    This is a long paper; a term project on this paper can focus on the tabular setting.

- **Algorithms for solving POMDPs**

   See the remark at the end of the notes on [POMDPs](pomdps/intro.qmd)






