::: {#exr-newsvendor-qualitative}

# Qualitative properties of optimal solution

Intuitively, in @exm-newsvendor, we expect that if the purchase price of the newspaper increases but the selling price remains the same, then the newsvendor should buy fewer newspapers. Formally prove this statement.

_Hint_: The CDF of a distribution is a weakly increasing function.

:::

::: {#exr-newsvendor-monotonicity}

# Monotonicity of optimal action

Consider two scenarios for the case with continuous demand and actions in @exm-newsvendor. In scenario 1, the demand is distributed according to PDF $f_1$. In scenario 2, it is distributed according to PDF $f_2$. Suppose $F_1(w) \le F_2(w)$ for all $w$. Show that the optimal action $a_1$ for scenario 1 is greater than the optimal action $a_2$ for scenario 2. 

 _Hint_: Plot the two CDFs and try to interpret the optimal decision rule graphically.

:::

::: {#exr-newsvendor-wind}
# Selling random wind

The amount $W$ of power generated by the wind turbine is a positive real-valued random variable with probability density function $f$. The operator of the wind turbine has to commit to provide a certain amount of power in the day-ahead market. The price of power is $\$p$ per MW. 

If the operator commits to provide $a$ MW of power and the wind generation $W$ is less than $a$, then he has to buy the balance $a - W$ from a reserves market at the cost of $\$ q$ per unit, where $q > p$. Thus, the reward of the operator is $r(a,W)$ where
$$ r(a, w) = \begin{cases}
  p a, & \text{if } w > a \\
  p a - q (a  - w), & \text{if } w < a.
\end{cases}$$

Find the optimal commitment $a$ that maximizes the expected reward.

:::


