---
execute:
  echo: false
---

# Assignment 1 {.unnumbered}

The purpose of this assignment is to review the background knowledge needed for this course. 

1. A fair coin is tossed twice, where the two tosses are independent. Let $Ω = \{ \mathsf{H}, \mathsf{T} \} × \{ \mathsf{H}, \mathsf{T} \}$ denote the sample space. 

   a. Describe the $σ$-algebra $\ALPHABET F$ and a probability function 
      $\PR \colon \ALPHABET F \to [0,1]$ such that $(Ω, \ALPHABET F, \PR)$ is a probability space.

   b. Verify that $\PR$ satisfies the axioms of probability. 

   c. Let $X$ be a random variable that counts the number of heads. Find the probability mass function and the cumulative density function of $X$.


2. Suppose $X$ and $Y$ are random variables that are uniformly distributed in the shaded region shown in @fig-2025-mid-term-1. Compute
   $$
     \PR( X - Y < 1 \mid Y < 2). 
   $$

```{ojs}
//| output: false

f_X_Y_2025_mid_term_1 = [
  {x: 0, y: 0},
  {x: 4, y: 0},
  {x: 4, y: 4},
  {x: 0, y: 0},
];

f_X_Y_2025_mid_term_1_A = [
  {x: 0, y: 0},
  {x: 4, y: 4},
];

f_X_Y_2025_mid_term_1_A_2 = [
  {x: 1, y: 0},
  {x: 4, y: 3},
];

f_X_Y_2025_mid_term_1_B = [
  {x: 0, y: 0},
  {x: 4, y: 0},
  {x: 4, y: 2},
  {x: 2, y: 2},
  {x: 0, y: 0},
];
```

```{ojs}
//| label: fig-2025-mid-term-1
//| fig-cap: "The joint PDF $f_{X,Y}$ is uniform in the shaded region and zero outside."
//| output: asis

Plot.plot({
  grid: true,
  width: 300,
  height: 300,
  marks: [
    // Axes
    Plot.ruleX([0]),
    Plot.ruleY([0]),
    // Data
    Plot.areaY(f_X_Y_2025_mid_term_1, {x: "x", y: "y", fill: "lightblue"}),
    Plot.line(f_X_Y_2025_mid_term_1, {x: "x", y: "y", stroke: "black"}),
  ]
})
```

3. Suppose $X_1 \sim \text{Binomial}(2, \tfrac 12)$ and $X_2 \sim \text{Binomial}(1, \tfrac 12)$ are independent random variables, and $Y = X_1 + X_2$. Find $\EXP[X_1 \mid Y]$.

4. A fair coin is tossed repeatedly until the sequence HHT shows up. Model this as a Markov chain and compute the expected number of coin tosses until stopping.

