project:
  type: website
  output-dir: slides/_site
  render:
    - slides/index.qmd
    - slides/static-optimization.qmd
    - slides/dynamic-programming.qmd
    - slides/lecture-03.qmd
    - slides/model-approximation.qmd
    - slides/lecture-05.qmd
    - slides/sample-path-bounds.qmd
    - slides/lecture-07.qmd
    - slides/lecture-08.qmd
    - slides/lecture-09.qmd
    - slides/lecture-10.qmd

format:
  revealjs:
    theme: [default, slides/custom.scss]
    fragments: true
    slide-number: true
    width: 1280
    height: 720
    margin: 0.04
    html-math-method: mathjax
    include-in-header:
      - ../static/html/mathjax.html
      - ../static/html/clicky.html
      - slides/tailwind.html
    css: slides/local.css

bibliography: ../references.bib
csl: ../_extensions/csl/acm-siggraph.csl
