project:
  type: book

book:
  title: Model approximation in MDPs and POMDPs
  author:
    - name: Aditya Mahajan
      url: "https://adityam.github.io"
      affiliation: McGill University
      affiliation-url: "https://www.mcgill.ca/ece"
  description: "Lecture notes CNI Summer School 2026"
  chapters:
    - index.qmd
    - part: "Exact models"
      chapters:
        - lectures/lecture-01.qmd
        - lectures/lecture-02.qmd
        - lectures/lecture-03.qmd
        - lectures/lecture-04.qmd
        - lectures/lecture-05.qmd
    - part: "Approximate models"
      chapters:
        - lectures/lecture-06.qmd
        - lectures/lecture-07.qmd
        - lectures/lecture-08.qmd
        - lectures/lecture-09.qmd
        - lectures/lecture-10.qmd

bibliography: ../references.bib
csl: ../_extensions/csl/acm-siggraph.csl

format:
  html:
    theme: lumen
    number-sections: true
    toc: true
    include-in-header:
      - ../static/html/mathjax.html
