project:
  type: book

book:
  title: Model approximation in MDPs and POMDPs
  author:
    - name: Aditya Mahajan
      url: "https://adityam.github.io"
      affiliation: McGill University
      affiliation-url: "https://www.mcgill.ca/ece"
  description: "Lecture notes CNI Summer School 2026"
  chapters:
    - index.qmd
    - lectures/static-optimization.qmd
    - lectures/dynamic-programming.qmd
    - lectures/MDP-properties.qmd
    - lectures/model-approximation.qmd
    - lectures/state-abstraction.qmd
    - lectures/sample-path-bounds.qmd

bibliography: ../references.bib
csl: ../_extensions/csl/acm-siggraph.csl

format:
  html:
    theme: lumen
    number-sections: true
    toc: true
    css: lectures/local.css
    include-in-header:
      - ../static/html/mathjax.html
      - ../static/html/clicky.html
