Consider the decision problem  by a person selling an asset. Let $W_t$
denote the offer received by the person at time $t$. We assume that
$\{W_t\}_{t \ge 1}$ is an i.i.d.\ process.
If the person sells the asset at time $t$, then he receives a reward equal
to the best offer received so far, i.e., $\max\{W_1, \dots, W_t\}$. If he
decides to continue, then he has to pay a continuation cost of $c$. Show
that there exist a sequence of thresholds $\{λ_t\}_{t \ge 1}$ such that
the optimal strategy is to sell the asset when $\max\{W_1, \dots, W_t\}
\ge λ_t$. 
