---
title: Infinite product of matrices
---

If $\{B_n\}_{n \ge 1}$ are $p \times p$ real matrices, we define
$$
    \prod_{k=n}^m B_k = 
    \begin{cases} 
        B_m B_{m-1} \cdots B_n & \hbox{if } n \le m, \\
        I & \hbox{if } n > m;
    \end{cases}
$$
to be the product where successive terms multiply on the left. 

We say that an infinite product $\prod_{n=1}^\infty B_n$ of $p \times p$ matrices converges if there exists an integer $N$ such that
$$
    Q = \lim_{m \to \infty} \prod_{n=N}^m B_n 
$$
exists. In this case, we define $\prod_{n=1}^\infty B_n = Q \prod_{n=1}^{N-1} B_n$. 

Following @Trench1999, we say that the product $\prod_{n=1}^\infty B_n$ converges _invertibly_ if for all $n \ge N$, $B_n$ is invertible and the product $Q$ defined above is invertible as well.  It was argued in @Trench1999 that the above definition has the following consequences:

- **(P1)** An invertibly convergent infinite product is singular if and only if at least one of its factors is singular.
- **(P2)** If $\prod_{n=1}^\infty B_n$ converges invertibly then $\lim_{n \to \infty} B_n = I$.

We now present some sufficient conditions for convergence of infinite product of matrices. If the matrices being multiplied are invertible, then the product converges to an invertible limit. Let $\NORM{\cdot}$ denote any sub-multiplicative matrix norm on $\reals^{p \times p}$ 

- **(C1)** If 
    $$ 
        \sum_{n=1}^{\infty} \NORM{B_n} < \infty
    $$
    then  $\prod_{n=1}^\infty (I + B_n)$  converges.
    

    
- **(C2)** Let $\{R_n\}_{n \ge 1}$ be a sequence of $p \times p$ matrices such that 
    $$
    \lim_{n \to \infty} R_n = I
    $$
    and 
    $$
    \sum_{n=1}^{\infty} \NORM{ (I + B_n) R_n - R_{n+1} } < \infty
    $$
    then $\prod_{n=1}^{\infty}(I + B_n)$ converges.
    
- **(C3)** Let $\{U_n\}_{n \ge 1}$ be a sequence of \emph{invertible} $p \times p$ matrices such that $\NORM{U_n} = 1$ for all $n$, there exists a $N$ such that $\prod_{n=N}^m U_n$ converges for $m \to \infty$, and 
    $$ 
        \sum_{n=1}^{\infty} \NORM{B_n} < \infty
    $$
    then  $\prod_{n=1}^\infty (U_n + B_n)$  converges.

## Exercises {-} 

:::{#exr-infinite-product-ar}
Suppose $A_t = \MATRIX{0 & 1 + \beta_t \\ 1 & \gamma_t}$, where $\beta_t, \gamma_t \in \reals_{\ge 0}$ Show that $\prod_{t \ge 1} A_t$ converges if
$$
  \sum_{t \ge 1} (\beta_t + \gamma_t) < \infty.
$$

_Hint_: Write $A_t = P + B_t$, where $P = \MATRIX{0 & 1 \\ 1 & 0}$ is a permultation matrix. So $P^2 = I$. Break the product $\prod_{t \ge 1} A_t$ as
$$
  \cdots (A_4 A_3) (A_2 A_1)
$$
and write $A_{2t}A_{2t-1}$ in the form $I + C_t$ and use property (C1).
:::

## Notes {-}

Condition (C1) is a standard result and stated as Theorem 1 in @Trench1999. Condition (C2) is Theorem 5 of @Trench1999. Condition (C3) is Theorem 2.1 combined with the remark on page~15 of @Artzrouni1986.

@exr-infinite-product-ar is from @Mahajan:cdc2024a.


