---
title: Regularized MDPs
draft: true
---

## Prelim: Legendre-Fenchel transform

Let $Ω \colon Δ(\ALPHABET A)$ to \reals$ be a strongly convex function. The Legendre-Fenchel transform (or convex conjugate) of $Ω$ is $Ω^* \colon [\ALPHABET A \to \reals] \to \reals$ defined as follows: for any $q \colon \ALPHABET A \to \reals$, 
$$
  Ω^*(q) = \max_{π \in Δ(\ALPHABET A)} \bigl\{ \langle π, q \rangle - Ω(π) \bigr\}.
$$

### A one-dimensioanl example of Legendre-Fenchel transform

Let $g$ be a real-valued, increasing, continuous function on $\reals$ which satisfies $g(0) = 0$, $g(x) \to -∞$ as $x \to -∞$ and $g(x) \to ∞$ as $x \to ∞$. Its inverse function $g^{-1}$ is well defined and has the same properties as $g$. Hence, if we define functions
$$
  f(x) = \int_{0}^x g(s) ds, \quad \forall x \in \reals,
  \qquad
  f^*(y) = \int_{0}^y g^{-1}(t) dt, \forall y \in \reals
$$
then $f$ and $f^*$ are both strictly convex on $\reals$. 

[ Add a figure showing both ]

The following results follow from the definitions of $f$ and $f^*$.

:::{#thm-Legendre-Fenchel-properties}
1. **Young's inequality.** $xy \le f(x) + f^*(y)$ for all $x$ and $y$ in $\reals$. 
2. $xy = f(x) + f^*(y)$ if and only if $y = f'(x)$. 
3. $(f^*)' = (f')^{-1}$.
4. $f^*(y) = \sup_{x \in \reals} \bigl\{ xy - f(x) \bigr\}$ for all $y \in \reals$.
5. $f(x) = \sup_{y \in \reals} \bigl\{ xy - f^*(x) \bigr\}$ for all $y \in \reals$.
:::

Note that property 4 gives the standard definition of Legendre-Fenchel transforms and property 5 shows that $f^{**} = f$.

:::{#prp-Legendre-transform}
Let $Ω$ be strongly convex. Then, we have following properties:

1. *Unique maximizing argument*: $\nabla Ω^*$ is Lipschitz and satisfies $\nabla Ω^*(q) = \arg\max_{π \in Δ(\ALPHABET A)}\bigl\{ \langle π, q \rangle - Ω(π)$ \bigr\}. 

2. *Boundedness*: If there are constants $L_{Ω}$ and $U_{Ω}$ such that for all $π \in Δ(\ALPHABET A)$, we have $L_{Ω} \le Ω(π) \le U_{Ω}$, then 
   $$
      \max_{a \in \ALPHABET A} q(a) - U_{Ω} \le Ω^*(q) \le 
      \max_{a \in \ALPHABET A} q(a) - L_{Ω}.
   $$
:::


A classical example is the negative entropy $Ω(π) = \sum_{a \in \ALPHABET A} π(a) \ln π(a)$. Its convex conjugate is the smoothend maximum $Ω^*(q) = \ln \sum_{a \in \ALPHABET A} \exp(q(a))$ and the unique maximizing element is the usual softmax $\nabla Ω^*(q) = \exp q(a)/\sum_{b \in \ALPHABET A} \exp q(b)$. 

